### ISSUE TITLE
interface disappearing

### ISSUE THREAD

**Issue by Rockawear** [amazonlinux/amazon-ec2-net-utils#52] opened 2022-05-25 17:16 UTC
Hi, 
We're running version 1.6.1 on Amazon Linux 2, instance provisioned with static private IPs through cloudformation. Sometimes it got to a state where any of the interface got in a bad state. and `ip addr` would display the interface but without an assigned ip address. Restarting network would bring it back. I have instances running 1.5.3 and I'm not seeing this issue. I'm not sure if this is already reported. is the tool causing this issue? it feels like IMDSv2 is failing because of token. How is that provided to the tool? 

Each interface config file has this entry.
`BOOTPROTO=dhcp`

from `/var/log/messages`
`
May 25 09:41:56 test-server dhclient[2953]: DHCPREQUEST on eth1 to xxx.xxx.xxx.xxx port 67 (xid=0xb7ed6ba)
May 25 09:41:56 test-server dhclient[2953]: DHCPACK from xxx.xx.xx.x (xid=0xb7ed6ba)
May 25 09:41:56 test-server ec2net: [get_meta] Querying IMDS for meta-data/network/interfaces/macs/xx:xx:xx:xx:xx:xx/local-ipv4s
May 25 09:41:56 test-server ec2net: [get_meta] Getting token for IMDSv2.
May 25 09:42:26 test-server ec2net: [get_meta] Failed to get IMDSv2 metadata token after 60 attempts... Aborting
May 25 09:42:26 test-server ec2net: [rewrite_rules] Could not get IPv4 addresses for eth1 from IMDS. Aborting
May 25 09:42:26 test-server ec2net: [get_meta] Querying IMDS for meta-data/network/interfaces/macs/xx:xx:xx:xx:xx:xx/local-ipv4s
May 25 09:42:26 test-server ec2net: [get_meta] Getting token for IMDSv2.
May 25 09:42:26 test-server dhclient[2953]: bound to xxx.xx.xx.xxx -- renewal in 1588 seconds.
May 25 09:42:57 test-server ec2net: [get_meta] Failed to get IMDSv2 metadata token after 60 attempts... Aborting
May 25 09:42:57 test-server ec2net: [rewrite_aliases] Failed to get secondary IPs from IMDS. Aborting
`

**Comment by Rockawear** [comment] 2022-05-25 18:36
I'm not changing anything IMDS. At least not that I'm aware of.

**Comment by nmeyerhans** [comment] 2022-05-26 23:57
Yeah, I've confirmed that the instance will still renew DHCP leases and maintain its network configuration even if IMDS goes away, which is expected as it's fairly common to disable IMDS access after initial instance setup.

> Obviously, if the issue affects eth0 this curl will fail.

So you've seen this behavior on eth0 as well as on secondary interfaces? That's a relevant detail because eth0 is handled slightly differently.

Can you share the full output of `ip addr`, `ip rule`, and `ip route show table all` from an instance that is experiencing this issue?

The logs you originally provided seem to indicate that the DHCP lease is successfully renewed, and nothing indicates that anything is removing routes or address configuration, so we'll need to collect some more data.

You can enable tracing on the dhclient-script by creating the file `/etc/dhcp/dhclient-enter-hooks.d/01_debug.sh` with content `exec 2>> /tmp/dhclient-debug.log ; set -x` and setting the execute bit on it (`chmod +x /etc/dhcp/dhclient-enter-hooks.d/01_debug.sh`). If you can install that and leave it in place on a working instance until a failure occurs, then send me the output of `journalctl -t ec2net -t dhclient` and the content of `/tmp/dhclient-debug.log`, that may provide some clues.

**Comment by Rockawear** [comment] 2022-05-27 15:13
@nmeyerhans I have an open case with AWS support. can I upload the logs there? Due to security concerns I can't upload them on here.

**Comment by nmeyerhans** [comment] 2022-05-27 15:18
>    ***@***.*** I have an open case with AWS support. can I upload the logs
>    there? Due to security concerns I can't upload them on here.

I don't have access to AWS support cases.  You can email the logs to me.
I am nmeyerha at amazon.com

**Comment by nmeyerhans** [comment] 2022-08-30 04:18
This was fixed in a recent update to the dhcp packages on Amazon Linux 2:
```plain
[ec2-user@ip-10-0-0-237 ~]$ rpm -q --changelog dhclient | head -n 2
* Wed Aug 03 2022 Dirk Harms-Merbitz <dhm@amazon.com> 4.2.5-79.amzn2.1.1
- Backport fix for negative timestep. RedHat RHBA-2020:1087
```

**Closed by nmeyerhans** 2022-08-30 04:18 UTC
