### ISSUE TITLE
Going from v1.7.0 to v1.7.1 caused instance to be unreachable

### ISSUE THREAD

**Issue by donaldi** [amazonlinux/amazon-ec2-net-utils#69] opened 2022-09-22 15:35 UTC
After updating a t3 instance (AWS Linux 2) to v1.7.1 (and rebooting) it started as normal but was unreachable, either from private or public (elastic) IP addresses.

Logging in via the serial tty, I could connect from the instance to the public internet without any trouble; it was only inbound connections that seemed affected.

Tried disassociating/re-associating the instance's elastic IP, as well as a full stop-then-start cycle, but that had no effect.

Tried restoring a backup copy of the instance -- this came online fine, but after a `yum update`  it showed the exact same behaviour (reachable only via serial tty). 

Performing a yum downgrade to v. 1.7.0 restored the instance's visibility.

Note that this is not a general bug, as I tested the update on a near-identical T3 dev server first and it seemed to work fine. It only caused the issue with the live server (of course). But I lack the networking smarts to pinpoint what the exact combination of circumstances that triggers the issue is -- however, reporting in case it may help someone else.

**Comment by kannansalem** [comment] 2022-09-23 04:34
Even my cx faced same issue, after upgrade the package from ec2-net-utils from 1.7.0 to 1.7.1 then instance went unreachable after reboot on kernel version 5.15.57-29.131.amzn2.x86_64. After reboot the console logs shows 

[  305.453508] cloud-init[2064]: Sep 22 05:50:40 cloud-init[2064]: util.py[WARNING]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_metadata.pyc'>) failed
[FAILED] Failed to start Initial cloud-init job (metadata service crawler).

**Comment by nmeyerhans** [comment] 2022-09-23 15:14
Thank you for these reports, I'll look into it. If it's at all possible to extract a complete set of logs from an impacted instance, that'd be helpful. In the worst case, you should be able to stop such an instance, detach its root EBS volume, and attach the volume to a second instance.

**Comment by nmeyerhans** [comment] 2022-09-23 21:14
I've been trying to reproduce this today, and over the course of several hundred primarily t3.micro and t3a.medium launches have been unable to do so thus far.

Some instance I've updated to kernel 5.15.y, since that was noted in the updated from @kannansalem, while others have used 5.10.

My process effectively involves executing `yum -y update ec2-net-utils && amazon-linux-extras install kernel-5.15 && reboot` using AMI amzn2-ami-kernel-5.10-hvm-2.0.20220805.0-x86_64-gp2 (ami-0c2ab3b8efb09f272 in us-west-2)

There may be other factors involved. Any more details about instance types, instance modifications (e.g. package installs, config changes, etc) that anybody can provide will be helpful.

**Comment by donaldi** [comment] 2022-09-25 19:10
Thanks for looking into this, happy to provide any help I can. As I say, I only saw this on one of my T3 instances, the other one was unaffected, so it is clearly some subtle interaction with the update and the installed software. The instance was a standard T3-class "small", running AWS Linux 2 with all packages updated to latest versions. Kernel is 4.14.291-218.527. I attach the boot log, and can add in any other logs you think would be of use.
[boot.log](https://github.com/amazonlinux/amazon-ec2-net-utils/files/9641578/boot.log)

**Comment by nmeyerhans** [comment] 2022-09-25 19:53
@donaldi thanks for sending in the boot log.  The log looks normal, with both IPv4 and IPv6 addresses and routes configured successfully. Was that supposed to be an example of a failure? If so, then the failure appears to have been somewhere else, as network configuration has seemingly occurred with no issues.

**Comment by donaldi** [comment] 2022-09-26 09:24
Yes, that's correct, I booted the instance up and obtained that log via the serial tty as it was unreachable ("no route to host") via internet. 

Cloning the instance, logging in via serial, then downgrading to v1.7.0 is the only way I can get it online (with my limited understanding of what is going on). If it would help I can share a snapshot of the instance with you, it has code on it which I am not able to make public, but it isn't hugely confidential. Alternatively if there are any other logs that would shed light on why the instance isn't reachable I would be happy to provide them. 

Attempting to do a reachability analysis via the AWS console shows the instance is "reachable", however any attempt to ssh into it (or access the website running on it) fails with a "no route to host" error. It's very odd.

**Comment by donaldi** [comment] 2022-09-30 15:16
I have been doing some more experimentation on this. I decided to try and get a better idea as to what **53-ec2-network-interfaces.rules** is doing, so temporarily replaced this line:

`ACTION=="add", SUBSYSTEM=="net", KERNEL=="eth*", DEVPATH!="/devices/virtual/*", RUN+="/usr/bin/systemctl start --no-block ec2net-ifup@$env{INTERFACE}"`

with this:

`ACTION=="add", SUBSYSTEM=="net", KERNEL=="eth*", DEVPATH!="/devices/virtual/*", RUN+="/bin/sh -c 'echo == >> /home/donald_i/udev.txt; env >> /home/donald_i/udev
.txt'"`

so I could see what variables were in _env_ and what they were set to. (The results of this are attached below, though nothing seemed out of the ordinary.) But to my surprise, when I rebooted the instance with this -- in effect -- NOOP udev rule, my instance was reachable via the internet again on its public IP address.

Putting the udev rule back and rebooting -- changing nothing else -- again gave me a "No route to host" when attempting to connect, and I was back to only having serial tty connectivity. 

Does that shed any light on what might be going on? If the eth0 interface works without this udev rule is something else configuring it elsewhere and causing a conflict? What would you expect to see if this udev rule was not run on boot?

[udev.txt](https://github.com/amazonlinux/amazon-ec2-net-utils/files/9685678/udev.txt)

**Comment by donaldi** [comment] 2022-10-03 16:17
Please close this thread if it is a complete wild-goose chase and relevant only to me, but whilst it is open I'm continuing to post my experiments/observations on this. (Hampered by my own ignorance.)

1. Didn't think to try it before now, but IPv6 address is functioning correctly, and remote SSH + HTTP access is possible, even while IPv4 address gives "no route to host". However, `ip a` shows a valid IPv4 address is associated with eth0.

>  eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 0a:ca:d0:7d:36:73 brd ff:ff:ff:ff:ff:ff
    inet 172.30.0.92/24 brd 172.30.0.255 scope global dynamic eth0
       valid_lft 2871sec preferred_lft 2871sec
    inet6 2a05:d018:fb7:b600:f327:7897:6440:3707/128 scope global dynamic 
       valid_lft 423sec preferred_lft 113sec
    inet6 fe80::8ca:d0ff:fe7d:3673/64 scope link 
       valid_lft forever preferred_lft forever

2. The instance running v1.7 (which is accessible as it should be over IPv4) gives this output to `systemctl status ec2net-ifup@eth0`:

> ● ec2net-ifup@eth0.service - Enable elastic network interfaces eth0
   Loaded: loaded (/usr/lib/systemd/system/ec2net-ifup@.service; static; vendor preset: disabled)
   Active: inactive (dead)
Condition: start condition failed at Dia 2022-09-22 15:20:35 UTC; 1 weeks 4 days ago
           ConditionPathExists=!/var/run/dhclient-eth0.pid was not met

This is what I'd expect. However, running the same command on the same (cloned) instance running v1.7.1 I get this output:

> ● ec2net-ifup@eth0.service - Enable elastic network interfaces eth0
   Loaded: loaded (/usr/lib/systemd/system/ec2net-ifup@.service; static; vendor preset: disabled)
   Active: inactive (dead)

Ie, the last log line about "start condition failed" is missing from the status. Admittedly it still seems to be inactive/dead, but given the two instances are running the identical software aside from net utils, it seems weird the message from systemctl isn't exactly the same. Yet the referenced pid file _is_ where it should be (at least, after the system has booted).

**Comment by nmeyerhans** [comment] 2022-10-26 16:08
Hi @donaldi Have you made any progress in your investigation? The logs I've seen so far look normal. The output included in your previous comment is also normal (`ec2net-ifup@eth0.service` is expected to be inactive; we only run that on hotplug, not on (re)boot. Since eth0 is never hotplugged, that service never actually runs.)

ec2-net-utils itself doesn't do anything that could specifically impact connectivity on _public_ IP addresses; it doesn't actually know anything about the instance's public IP and relies entirely on the VPC infrastructure to handle mapping between private and public IPv4 addresses.

What do your IPv4 routing tables and policy rule configuration look like when an instance is impaired?  Can you post the output of `ip -4 ro show table all` and `ip -4 rule`?

You might also try using the [VPC Reachability Analyzer](https://docs.aws.amazon.com/vpc/latest/reachability/getting-started.html) to gather more information about your instance's connectivity relative to arbitrary network addresses.

**Comment by donaldi** [comment] 2022-10-28 14:56
Hi there, not made any further progress. The output from both `ip -4` commands is identical when the host is in the unreachable state and when it is reachable via its public IP.

The VPC reachability analyzer claims it _is_ reachable, yet neither I nor the ELB can get to it via its public IP.

The host is unreachable 100% of the time with the `no route to host` when the ec2-network-interfaces.rules file has the `add` action left in and is (conversely) reachable 100% of the time if I replace it with a no-op call that doesn't reference `ec2net-ifup`. I've tested this over quite a few reboots and it seems to be true every time.

However, I've (cautiously) upgraded a few other of my t instances to v1.7.1 and they all worked as they should, so this must be some really strange combo of circumstances that applies to this instance only (as you've proved with your own experiments). I will probably work around this by postponing the update until the RI I have for the t3 runs out and migrating to a t4 instance.

**Comment by nmeyerhans** [comment] 2023-06-05 21:11
Closing this for now, but please feel free to re-open if you find anything that might help move it forward.

**Closed by nmeyerhans** 2023-06-05 21:11 UTC
